extraction:
    cpp:
        prepare:
            packages:
                - libcurl4-openssl-dev
                - libjansson-dev
        after_prepare:
            - cd $LGTM_WORKSPACE
            - git clone https://github.com/ac000/libmtdac.git
            - cd libmtdac/src
            - make
            - export LD_LIBRARY_PATH=`pwd`
            - cd $LGTM_SRC
        index:
            build_command:
                - CFLAGS=-I${LGTM_WORKSPACE}/libmtdac/include LDFLAGS=-L${LGTM_WORKSPACE}/libmtdac/src make
